name: Generate Pac-Man Game

on:
  schedule:
    # Run automatically every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch: # Allows manual triggering
  push:
    # Runs on every push to the main branch
    branches:
      - main

permissions:
  contents: write  # Ensure the GitHub Actions bot can push changes to the repository

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pac-Man Contribution Graph
        uses: abozanona/pacman-contribution-graph/github-action@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Push Pac-Man Graph to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
